### ISSUE TITLE
Implementation of Taxii  2.0 client APIs

### ISSUE THREAD

**Issue by monikaDesai** [StephenOTT/TAXII-springboot-bpmn#27]

**Comment by StephenOTT** [comment]
@monikaDesai  you can track usage here https://github.com/StephenOTT/TAXII-springboot-bpmn/tree/master/src/main/java/io/digitalstate/taxii/endpoint

**Comment by StephenOTT** [comment]
@monikaDesai the endpoints have been implemented and are fully functional.  Further enhancements and cleanups are being made, but all of the core requirements are there.
